### PR TITLE
Redistribution of Stardog is a direct violation of the end-user license

### PR DESCRIPTION
**Pull request by mhgrove**

### CODE REVIEW

**Comment by k00ni** [comment]
@mhgrove: Sorry to hear, i was not aware of that. I think there is a sophisticated docker image available to use instead? We will handle that and will shut down this repository until next week.

@simeonackermann: can you please check what a removal of this repository means for our work? Is it possible to replace it with the standard container of Stardog?

**Comment by mhgrove** [comment]
@k00ni we provide docker images for our customers. we do not provide one for community use

**Comment by k00ni** [comment]
@mhgrove: Are the following Stardog Docker containers suitable for non-commercial/community usage?
- https://hub.docker.com/r/bluepeppers/stardog/
- https://hub.docker.com/r/nice/ld-docker-stardog

I read about a "Stardog Community" version on your site[1], but it doesn't mean that the software is open for public usage in general, right? You need a key from Stardog company. 

Our goal by providing a container is to use it as a backend for Linked Data applications, such as OntoWiki[2]. If the mentioned containers are suitable, we will try them next. If they are also violate your end use license, what would you propose?

[1] http://stardog.com/#download
[2] http://stardog.com/#download

**Comment by mhgrove** [comment]
No, they're both violating the terms of the license as well.

The community version of the software grants you the rights to _use_ Stardog, but you *cannot* redistribute any part of it, not the binary and it absolutely does not grant you the ability to distribute the license.

I recommend you contact sales@stardog.com to discuss the options you have available to you.

**Comment by kendall** [comment]
@k00ni The *only* option is to take this down now. It's a clear violation of the license. Please let me know when you can comply. Thanks!

**Comment by k00ni** [comment]
@kendall and @mhgrove: Just wanted to let you know, that i will remove this repository now. Sorry for any trouble.

**Pull request closed without merging**
